export const MOVIESWATCHING = [
  {
    id: "1",
    name: "Toda a família tem",
    moviesURL: require("../assets/movies/toda_a_familia.png"),
    description: "Um drama emocionante sobre os altos e baixos das relações familiares.",
    duration: "1h 45min",
    genre: "Drama, Comédia",
    rating: "7.8/10",
    cast: "Jane Doe, John Smith, Emily Brown",
  },
  {
    id: "2",
    name: "Sob a luz de outono",
    moviesURL: require("../assets/movies/Sob_a_luz.png"),
    description: "Uma história cativante de amor e segredos revelados sob o sol de outono.",
    duration: "2h 10min",
    genre: "Romance, Drama",
    rating: "8.2/10",
    cast: "Alice Johnson, Michael Green, Emma White",
  },
  {
    id: "3",
    name: "The Vampire Diaries",
    moviesURL: require("../assets/movies/Vampire.png"),
    description: "A saga de vampiros, lobisomens e humanos em uma luta por poder e sobrevivência.",
    duration: "8 temporadas",
    genre: "Fantasia, Drama, Suspense",
    rating: "7.7/10",
    cast: "Nina Dobrev, Paul Wesley, Ian Somerhalder",
  },
  {
    id: "4",
    name: "Ela",
    moviesURL: require("../assets/movies/ela.png"),
    description: "Um homem desenvolve um relacionamento com uma inteligência artificial avançada.",
    duration: "2h 6min",
    genre: "Ficção Científica, Romance",
    rating: "8.0/10",
    cast: "Joaquin Phoenix, Scarlett Johansson, Amy Adams",
  },
  {
    id: "5",
    name: "O contato",
    moviesURL: require("../assets/movies/O_contato.png"),
    description: "Uma cientista recebe uma mensagem de uma civilização alienígena e embarca em uma jornada inesquecível.",
    duration: "2h 30min",
    genre: "Ficção Científica, Drama",
    rating: "7.4/10",
    cast: "Jodie Foster, Matthew McConaughey, Tom Skerritt",
  },
];
